general:
  productiveBranch: "main"
  buildTool: "mta"

stages:
  build:
    npmExecuteLint: false

  additionalUnitTests:
    npmExecuteScripts: false
    karmaExecuteTests: false

  acceptance:
    cloudFoundryDeploy: false

  release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "bddd1fcetrial"
    cfSpace: "dev"
    cfCredentialsId: "deploy-to-cf"

steps:
  mtaBuild:
    buildTarget: "CF"
    mtarName: "incident-management.mtar"

  cloudFoundryDeploy:
    deployTool: "mtaDeployPlugin"
    mtaPath: "mta_archives/incident-management.mtar"